/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SellRouteImport } from './routes/sell'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as CoursesBecomeRouteImport } from './routes/courses.become'
import { Route as CoursesDashboardRouteImport } from './routes/courses.dashboard'
import { Route as CoursesMyRouteImport } from './routes/courses.my'
import { Route as CoursesNewRouteImport } from './routes/courses.new'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as ServicesBecomeRouteImport } from './routes/services.become'
import { Route as ServicesDashboardRouteImport } from './routes/services.dashboard'
import { Route as ServicesNewRouteImport } from './routes/services.new'
import { Route as ServicesOrdersRouteImport } from './routes/services.orders'
import { Route as CoursesLearnIdRouteImport } from './routes/courses.learn.$id'
import { Route as ApiPublicAuthVerifyRouteImport } from './routes/api/public/auth.verify'
import { Route as ApiPublicPaymentsApproveRouteImport } from './routes/api/public/payments.approve'
import { Route as ApiPublicPaymentsCompleteRouteImport } from './routes/api/public/payments.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesBecomeRoute = CoursesBecomeRouteImport.update({
  id: '/courses/become',
  path: '/courses/become',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesDashboardRoute = CoursesDashboardRouteImport.update({
  id: '/courses/dashboard',
  path: '/courses/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesMyRoute = CoursesMyRouteImport.update({
  id: '/courses/my',
  path: '/courses/my',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesNewRoute = CoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBecomeRoute = ServicesBecomeRouteImport.update({
  id: '/services/become',
  path: '/services/become',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDashboardRoute = ServicesDashboardRouteImport.update({
  id: '/services/dashboard',
  path: '/services/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNewRoute = ServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOrdersRoute = ServicesOrdersRouteImport.update({
  id: '/services/orders',
  path: '/services/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesLearnIdRoute = CoursesLearnIdRouteImport.update({
  id: '/courses/learn/$id',
  path: '/courses/learn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthVerifyRoute = ApiPublicAuthVerifyRouteImport.update({
  id: '/api/public/auth/verify',
  path: '/api/public/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsApproveRoute =
  ApiPublicPaymentsApproveRouteImport.update({
    id: '/api/public/payments/approve',
    path: '/api/public/payments/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsCompleteRoute =
  ApiPublicPaymentsCompleteRouteImport.update({
    id: '/api/public/payments/complete',
    path: '/api/public/payments/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/sell': typeof SellRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/become': typeof CoursesBecomeRoute
  '/courses/dashboard': typeof CoursesDashboardRoute
  '/courses/my': typeof CoursesMyRoute
  '/courses/new': typeof CoursesNewRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/become': typeof ServicesBecomeRoute
  '/services/dashboard': typeof ServicesDashboardRoute
  '/services/new': typeof ServicesNewRoute
  '/services/orders': typeof ServicesOrdersRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/courses/learn/$id': typeof CoursesLearnIdRoute
  '/api/public/auth/verify': typeof ApiPublicAuthVerifyRoute
  '/api/public/payments/approve': typeof ApiPublicPaymentsApproveRoute
  '/api/public/payments/complete': typeof ApiPublicPaymentsCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/sell': typeof SellRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/become': typeof CoursesBecomeRoute
  '/courses/dashboard': typeof CoursesDashboardRoute
  '/courses/my': typeof CoursesMyRoute
  '/courses/new': typeof CoursesNewRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/become': typeof ServicesBecomeRoute
  '/services/dashboard': typeof ServicesDashboardRoute
  '/services/new': typeof ServicesNewRoute
  '/services/orders': typeof ServicesOrdersRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
  '/courses/learn/$id': typeof CoursesLearnIdRoute
  '/api/public/auth/verify': typeof ApiPublicAuthVerifyRoute
  '/api/public/payments/approve': typeof ApiPublicPaymentsApproveRoute
  '/api/public/payments/complete': typeof ApiPublicPaymentsCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/sell': typeof SellRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/become': typeof CoursesBecomeRoute
  '/courses/dashboard': typeof CoursesDashboardRoute
  '/courses/my': typeof CoursesMyRoute
  '/courses/new': typeof CoursesNewRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/become': typeof ServicesBecomeRoute
  '/services/dashboard': typeof ServicesDashboardRoute
  '/services/new': typeof ServicesNewRoute
  '/services/orders': typeof ServicesOrdersRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/courses/learn/$id': typeof CoursesLearnIdRoute
  '/api/public/auth/verify': typeof ApiPublicAuthVerifyRoute
  '/api/public/payments/approve': typeof ApiPublicPaymentsApproveRoute
  '/api/public/payments/complete': typeof ApiPublicPaymentsCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/orders'
    | '/sell'
    | '/courses/$id'
    | '/courses/become'
    | '/courses/dashboard'
    | '/courses/my'
    | '/courses/new'
    | '/product/$id'
    | '/services/$id'
    | '/services/become'
    | '/services/dashboard'
    | '/services/new'
    | '/services/orders'
    | '/courses/'
    | '/dashboard/'
    | '/services/'
    | '/courses/learn/$id'
    | '/api/public/auth/verify'
    | '/api/public/payments/approve'
    | '/api/public/payments/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/orders'
    | '/sell'
    | '/courses/$id'
    | '/courses/become'
    | '/courses/dashboard'
    | '/courses/my'
    | '/courses/new'
    | '/product/$id'
    | '/services/$id'
    | '/services/become'
    | '/services/dashboard'
    | '/services/new'
    | '/services/orders'
    | '/courses'
    | '/dashboard'
    | '/services'
    | '/courses/learn/$id'
    | '/api/public/auth/verify'
    | '/api/public/payments/approve'
    | '/api/public/payments/complete'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/orders'
    | '/sell'
    | '/courses/$id'
    | '/courses/become'
    | '/courses/dashboard'
    | '/courses/my'
    | '/courses/new'
    | '/product/$id'
    | '/services/$id'
    | '/services/become'
    | '/services/dashboard'
    | '/services/new'
    | '/services/orders'
    | '/courses/'
    | '/dashboard/'
    | '/services/'
    | '/courses/learn/$id'
    | '/api/public/auth/verify'
    | '/api/public/payments/approve'
    | '/api/public/payments/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  OrdersRoute: typeof OrdersRoute
  SellRoute: typeof SellRoute
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesBecomeRoute: typeof CoursesBecomeRoute
  CoursesDashboardRoute: typeof CoursesDashboardRoute
  CoursesMyRoute: typeof CoursesMyRoute
  CoursesNewRoute: typeof CoursesNewRoute
  ProductIdRoute: typeof ProductIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ServicesBecomeRoute: typeof ServicesBecomeRoute
  ServicesDashboardRoute: typeof ServicesDashboardRoute
  ServicesNewRoute: typeof ServicesNewRoute
  ServicesOrdersRoute: typeof ServicesOrdersRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  CoursesLearnIdRoute: typeof CoursesLearnIdRoute
  ApiPublicAuthVerifyRoute: typeof ApiPublicAuthVerifyRoute
  ApiPublicPaymentsApproveRoute: typeof ApiPublicPaymentsApproveRoute
  ApiPublicPaymentsCompleteRoute: typeof ApiPublicPaymentsCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/become': {
      id: '/courses/become'
      path: '/courses/become'
      fullPath: '/courses/become'
      preLoaderRoute: typeof CoursesBecomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/dashboard': {
      id: '/courses/dashboard'
      path: '/courses/dashboard'
      fullPath: '/courses/dashboard'
      preLoaderRoute: typeof CoursesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/my': {
      id: '/courses/my'
      path: '/courses/my'
      fullPath: '/courses/my'
      preLoaderRoute: typeof CoursesMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/new': {
      id: '/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof CoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/become': {
      id: '/services/become'
      path: '/services/become'
      fullPath: '/services/become'
      preLoaderRoute: typeof ServicesBecomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/dashboard': {
      id: '/services/dashboard'
      path: '/services/dashboard'
      fullPath: '/services/dashboard'
      preLoaderRoute: typeof ServicesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/new': {
      id: '/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ServicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/orders': {
      id: '/services/orders'
      path: '/services/orders'
      fullPath: '/services/orders'
      preLoaderRoute: typeof ServicesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/learn/$id': {
      id: '/courses/learn/$id'
      path: '/courses/learn/$id'
      fullPath: '/courses/learn/$id'
      preLoaderRoute: typeof CoursesLearnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/verify': {
      id: '/api/public/auth/verify'
      path: '/api/public/auth/verify'
      fullPath: '/api/public/auth/verify'
      preLoaderRoute: typeof ApiPublicAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/approve': {
      id: '/api/public/payments/approve'
      path: '/api/public/payments/approve'
      fullPath: '/api/public/payments/approve'
      preLoaderRoute: typeof ApiPublicPaymentsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/complete': {
      id: '/api/public/payments/complete'
      path: '/api/public/payments/complete'
      fullPath: '/api/public/payments/complete'
      preLoaderRoute: typeof ApiPublicPaymentsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  SellRoute: SellRoute,
  CoursesIdRoute: CoursesIdRoute,
  CoursesBecomeRoute: CoursesBecomeRoute,
  CoursesDashboardRoute: CoursesDashboardRoute,
  CoursesMyRoute: CoursesMyRoute,
  CoursesNewRoute: CoursesNewRoute,
  ProductIdRoute: ProductIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  ServicesBecomeRoute: ServicesBecomeRoute,
  ServicesDashboardRoute: ServicesDashboardRoute,
  ServicesNewRoute: ServicesNewRoute,
  ServicesOrdersRoute: ServicesOrdersRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  CoursesLearnIdRoute: CoursesLearnIdRoute,
  ApiPublicAuthVerifyRoute: ApiPublicAuthVerifyRoute,
  ApiPublicPaymentsApproveRoute: ApiPublicPaymentsApproveRoute,
  ApiPublicPaymentsCompleteRoute: ApiPublicPaymentsCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
