/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaymentsApproveRouteImport } from './routes/api/public/payments.approve'
import { Route as ApiPublicPaymentsCompleteRouteImport } from './routes/api/public/payments.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsApproveRoute =
  ApiPublicPaymentsApproveRouteImport.update({
    id: '/api/public/payments/approve',
    path: '/api/public/payments/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsCompleteRoute =
  ApiPublicPaymentsCompleteRouteImport.update({
    id: '/api/public/payments/complete',
    path: '/api/public/payments/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/payments/approve': typeof ApiPublicPaymentsApproveRoute
  '/api/public/payments/complete': typeof ApiPublicPaymentsCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/payments/approve': typeof ApiPublicPaymentsApproveRoute
  '/api/public/payments/complete': typeof ApiPublicPaymentsCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/payments/approve': typeof ApiPublicPaymentsApproveRoute
  '/api/public/payments/complete': typeof ApiPublicPaymentsCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/public/payments/approve' | '/api/public/payments/complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/payments/approve' | '/api/public/payments/complete'
  id:
    | '__root__'
    | '/'
    | '/api/public/payments/approve'
    | '/api/public/payments/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicPaymentsApproveRoute: typeof ApiPublicPaymentsApproveRoute
  ApiPublicPaymentsCompleteRoute: typeof ApiPublicPaymentsCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/approve': {
      id: '/api/public/payments/approve'
      path: '/api/public/payments/approve'
      fullPath: '/api/public/payments/approve'
      preLoaderRoute: typeof ApiPublicPaymentsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/complete': {
      id: '/api/public/payments/complete'
      path: '/api/public/payments/complete'
      fullPath: '/api/public/payments/complete'
      preLoaderRoute: typeof ApiPublicPaymentsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicPaymentsApproveRoute: ApiPublicPaymentsApproveRoute,
  ApiPublicPaymentsCompleteRoute: ApiPublicPaymentsCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
